version: '3'
services:
  amebo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    network_mode: host

  # redis:
  #   build: ./redis/.
  #   restart: always
  #   ports:
  #     - '6379:6379'