FROM golang:1.16.3-alpine AS builder
WORKDIR /app/
COPY go.mod .
COPY go.sum .
RUN go mod download
COPY . .

ARG MY_ID="1355670684551282688"
ARG STUB_TWEET="false"
ARG API_KEY="dWpQQRebwWISQx7wQT0Dt9M4x"
ARG API_SECRET_KEY="izah5ZXj7MJoYsAFIzUORHDASxxN13nDxmnd9PUzO9z1t70BS1"
ARG ACCESS_TOKEN="1355670684551282688-lHAf7P4HuVYMfkjP8Iw1RqikWk1LF2"
ARG ACCESS_TOKEN_SECRET="0vq1Ub12Od0ED8sGp7ye5DLw0wJ4WT0Tcbw6GrAxhqtoQ"
ARG BEARER_TOKEN="AAAAAAAAAAAAAAAAAAAAAB9vNQEAAAAAWXsAwaKj0rmG4MHIAkQD9WdAI8c%3DKuDoGip5QaCu0Ksl2bpJuDJzsOi9qLIGxNLcd6X53k9Pr67YMO"
ARG REDIS_HOST="localhost"
ARG REDIS_PORT="6379"

ENV MY_ID=${MY_ID}
ENV STUB_TWEET=${STUB_TWEET}
ENV API_KEY=${API_KEY}
ENV API_SECRET_KEY=${API_SECRET_KEY}
ENV ACCESS_TOKEN=${ACCESS_TOKEN}
ENV ACCESS_TOKEN_SECRET=${ACCESS_TOKEN_SECRET}
ENV BEARER_TOKEN=${BEARER_TOKEN} 
ENV REDIS_HOST=${REDIS_HOST}
ENV REDIS_PORT=${REDIS_PORT}

RUN go build -o executable .

FROM builder
WORKDIR /root/
COPY --from=builder /app/executable ./

CMD [ "./executable" ]


