version: '3'
services:
  amebo:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    depends_on:
      redis:
        condition: service_started
    network_mode: host

  redis:
    build: ./redis/.
    restart: always
    ports:
      - '6379:6379'