name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production_environment
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...
    - name: Docker Auth
      run: docker login -u "${{secrets.U}}" -p "${{secrets.P}}" docker.io
    - name: Build Image
      run:  | 
        docker build --build-arg \ 
          MY_ID="${{secrets.MY_ID}}" \ 
          STUB_TWEET="${{secrets.STUB_TWEET}}" \ 
          API_KEY="${{secrets.API_KEY}}" \ 
          API_SECRET_KEY="${{secrets.API_SECRET_KEY}}" \ 
          ACCESS_TOKEN="${{secrets.ACCESS_TOKEN}}" \ 
          ACCESS_TOKEN_SECRET="${{secrets.ACCESS_TOKEN_SECRET}}" \ 
          BEARER_TOKEN="${{secrets.BEARER_TOKEN}}" \ 
          --tag pbaba11/amebo:latest .
    - name: push to docker hub
      run: docker push pbaba11/amebo:latest
