name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production_environment
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...
    - name: Docker Auth
      run: docker login -u "{{env.U}}" -p "{{env.P}}" docker.io
    - name: Build Image
      run:  | 
        docker build --build-arg \ 
          MY_ID={{env.MY_ID}} \ 
          STUB_TWEET={{env.STUB_TWEET}} \ 
          API_KEY={{env.API_KEY}} \ 
          API_SECRET_KEY={{env.API_SECRET_KEY}} \ 
          ACCESS_TOKEN={{env.ACCESS_TOKEN}} \ 
          ACCESS_TOKEN_SECRET={{env.ACCESS_TOKEN_SECRET}} \ 
          BEARER_TOKEN={{env.BEARER_TOKEN}} \ 
          --tag=pbaba11/amebo:latest
    - name: push to docker hub
      run: docker push pbaba11/amebo:latest
