name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    runs-on: ubuntu-latest
    environment: production_environment
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Test
      run: go test -v ./...
    - name: Docker Auth
      run: docker login -u "${{secrets.U}}" -p "${{secrets.P}}" docker.io
    - name: Build Image
      run: docker build . --tag "pbaba11/amebo:latest" --build-arg MY_ID="${{secrets.MY_ID}}" --build-arg STUB_TWEET="${{secrets.STUB_TWEET}}" --build-arg API_KEY="${{secrets.API_KEY}}" --build-arg API_SECRET_KEY="${{secrets.API_SECRET_KEY}}" --build-arg ACCESS_TOKEN="${{secrets.ACCESS_TOKEN}}" --build-arg ACCESS_TOKEN_SECRET="${{secrets.ACCESS_TOKEN_SECRET}}" --build-arg BEARER_TOKEN="${{secrets.BEARER_TOKEN}}" 
    - name: push to docker hub
      run: docker push pbaba11/amebo:latest
    - name: Deploy to ECS
      run: docker run fabfuel/ecs-deploy:1.10.2 ecs deploy amebo-cluster amebo-service --region us-east-2 --access-key-id ${{secrets.ACCESS_KEY_ID}} --secret-access-key ${{secrets.SECRET_ACCESS_KEY}}